# Generated by Django 6.0.1 on 2026-02-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MECHANIC', 'Mechanic'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=20),
        ),
    ]
