# Generated by Django 6.0.1 on 2026-04-20 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='customer',
        ),
    ]
